# 配置端口
server:
  port: 9009
  servlet:
    application-display-name: crm-app

spring:
  datasource:
    # 基本属性
    name: dev
    url: jdbc:mysql://127.0.0.1:3306/db_crm?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    # 可以不配置，根据url自动识别，建议配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化连接池个数
    initialSize: 5
    # 最小连接池个数——》已经不再使用，配置了也没效果
    minIdle: 2
    # 最大连接池个数
    maxActive: 20
    # 配置获取连接等待超时的时间，单位毫秒，缺省启用公平锁，并发效率会有所下降
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句。
    # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
    validationQuery: SELECT 1 FROM DUAL
    # 建议配置为true，不影响性能，并且保证安全性。
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过别名的方式配置扩展插件，多个英文逗号分隔，常用的插件有：
    # 监控统计用的filter:stat
    # 日志用的filter:log4j
    # 防御sql注入的filter:wall
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 是否开启安全验证
management:
  security:
    enabled: false



# mybatis-plus相关配置
mybatis-plus:
  # xml扫描
  mapper-locations: classpath*:**/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: false
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      update-strategy: not_empty
  configuration:
    # 开启自动驼峰命名规则映p[[ ,射:DB的列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    # 将执行的sql打印出来
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

crm:
  swagger:
    title: CRM接口文档
    description: CRM接口文档
    version: 1.0.0
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:

  #安全认证
  nocheck:
    #单位分钟
    tokenExpireTime: 30
    #单位天数
    saveLoginTime: 30
    #单位次数
    loginTimeLimit: 5
    #单位分钟
    loginAfterTime: 15
    #不需要验证的url
    ignoreUrls:
      - /test
      - /login
      - /logout

      - /api/user/getInfo
      - /api/user/list
      - /api/user/page
      - /api/user/permissions

      - /api/role/list
      - /api/role/page
      - /api/role/commonList
      - /api/role/getAllMenus
      - /api/role/getPermissionById
      - /api/role/setMenus
      - /api/role/**
      - /api/role/save
      - /api/role/update
      - /api/role/delete

      - /api/menus/list
      - /api/menus/save
      - /api/menus/update
      - /api/menus/batchDelete
      - /api/menus/delete
      - /api/menus/getDict

      - /api/crm/clients/list
      - /api/crm/clients/page
      - /api/crm/clients/save
      - /api/crm/clients/update
      - /api/crm/clients/delete

      - /api/crm/contacts/page
      - /api/crm/contacts/save
      - /api/crm/contacts/update
      - /api/crm/contacts/delete

      - /api/crm/work/list
      - /api/crm/work/page
      - /api/crm/work/save
      - /api/crm/work/update
      - /api/crm/work/delete
      - /api/crm/work/**

      - /api/crm/opensea/page

      - /api/log/list

      - /index
      - /doc.html
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger-resources/configuration/ui
      - /swagger-resources
      - /v2/api-docs
      - /swagger-resources/configuration/security
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /druid/index.html
      - /**/druid/*
      - /sql
      - /**/druid/**
      - /druid/spring.json


# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: mqxu-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # token过期时间（分钟）
  tokenExpireTime: 30
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10